WITH CTE AS (
    SELECT
        CART_ID,
        NAME,
        SUM(CASE WHEN NAME = 'Milk' THEN 1 ELSE 0 END) MILK,
        SUM(CASE WHEN NAME = 'Yogurt' THEN 1 ELSE 0 END) YOGURT
    FROM CART_PRODUCTS
    GROUP BY CART_ID
    HAVING MILK > 0 AND YOGURT > 0
)

SELECT CART_ID FROM CTE ORDER BY CART_ID;