SELECT SALES_DATE, PRODUCT_ID, USER_ID, SUM(SALES_AMOUNT) SALES_AMOUNT
FROM (
    SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
    UNION
    SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') SALES_DATE, PRODUCT_ID, NULL USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
    WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
) S
GROUP BY SALES_DATE, PRODUCT_ID, USER_ID
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;
