WITH MAX_PLAN AS (
    SELECT 
        CAR_TYPE, 
        MAX(
            CASE 
                WHEN DURATION_TYPE = '30일 이상' THEN DISCOUNT_RATE 
                ELSE 0 
            END
        ) AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    GROUP BY CAR_TYPE
),
AVAILABLE_CARS AS (
    SELECT 
        C.CAR_ID, 
        C.CAR_TYPE, 
        C.DAILY_FEE, 
        IFNULL(P.DISCOUNT_RATE, 0) AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_CAR C
    LEFT JOIN MAX_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
    WHERE C.CAR_TYPE IN ('세단', 'SUV')
      AND C.CAR_ID NOT IN (
          SELECT CAR_ID 
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
          WHERE START_DATE <= '2022-11-30' 
            AND END_DATE >= '2022-11-01'
      )
)
SELECT 
    A.CAR_ID, 
    A.CAR_TYPE, 
    FLOOR((A.DAILY_FEE * 30) * (100 - A.DISCOUNT_RATE) / 100) AS FEE
FROM AVAILABLE_CARS A
WHERE (A.DAILY_FEE * 30) * (100 - A.DISCOUNT_RATE) / 100 BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC;
