SELECT
    YEAR(S.SALES_DATE) YEAR, 
    MONTH(S.SALES_DATE) MONTH, 
    I.GENDER GENDER, 
    COUNT(DISTINCT S.USER_ID) USERS
FROM ONLINE_SALE S
JOIN USER_INFO I
ON S.USER_ID = I.USER_ID
WHERE GENDER IN (0, 1)
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;
