WITH P AS (
    SELECT
        YEAR(O.SALES_DATE) YEAR,
        MONTH(O.SALES_DATE) MONTH,
        COUNT(DISTINCT O.USER_ID) COUNT
    FROM ONLINE_SALE O
    JOIN USER_INFO U
    ON O.USER_ID = U.USER_ID
    WHERE YEAR(U.JOINED) = '2021'
    GROUP BY YEAR, MONTH
), SUM_COUNT AS (
    SELECT COUNT(DISTINCT USER_ID) COUNT
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'
)

SELECT P.YEAR YEAR, P.MONTH MONTH, P.COUNT PURCHASED_USERS, ROUND(P.COUNT / S.COUNT, 1) PURCHASED_RATIO
FROM P P
JOIN SUM_COUNT S
ORDER BY YEAR, MONTH;

