WITH IMPOSSIBLE AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
    GROUP BY CAR_ID
)

SELECT 
    C.CAR_ID,
    CASE 
        WHEN I.CAR_ID IS NOT NULL THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
LEFT JOIN IMPOSSIBLE I ON C.CAR_ID = I.CAR_ID
GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC;
