WITH SUM_AMOUNT AS (
    SELECT PRODUCT_ID, SUM(AMOUNT) AMOUNT
    FROM FOOD_ORDER
    WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
    GROUP BY PRODUCT_ID
)

SELECT
    F.PRODUCT_ID PRODUCT_ID,
    F.PRODUCT_NAME PRODUCT_NAME,
    F.PRICE * S.AMOUNT TOTAL_SALES
FROM FOOD_PRODUCT F
JOIN SUM_AMOUNT S
ON F.PRODUCT_ID = S.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;