WITH PLAN AS (
    SELECT
        CAR_TYPE,
        CAST(SUBSTR(DURATION_TYPE, 1, LOCATE('일', DURATION_TYPE) - 1) AS UNSIGNED) AS DURATION_TYPE,
        (100 - CAST(SUBSTR(DISCOUNT_RATE, 1, LENGTH(DISCOUNT_RATE)) AS UNSIGNED)) AS FINAL_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
), HISTORY AS (
    SELECT 
        HISTORY_ID, 
        CAR_ID, 
        (DATEDIFF(END_DATE, START_DATE) + 1) AS DIFF
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
), RENTAL_FEES AS (
    SELECT
        H.HISTORY_ID AS HISTORY_ID,
        ROUND(H.DIFF * (C.DAILY_FEE * 
            (1 - IFNULL(P.DISCOUNT_RATE, 0) / 100)), 0) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN HISTORY H ON C.CAR_ID = H.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
      ON C.CAR_TYPE = P.CAR_TYPE 
      AND (
          (H.DIFF >= 90 AND P.DURATION_TYPE = '90일 이상') OR
          (H.DIFF BETWEEN 30 AND 89 AND P.DURATION_TYPE = '30일 이상') OR
          (H.DIFF BETWEEN 7 AND 29 AND P.DURATION_TYPE = '7일 이상')
      )
    WHERE C.CAR_TYPE = '트럭'
)

SELECT HISTORY_ID, FEE
FROM RENTAL_FEES
ORDER BY FEE DESC, HISTORY_ID DESC;
