WITH F AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR
), J AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
), A AS (
    SELECT * FROM F
    UNION
    SELECT * FROM J
), B AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
    FROM A
    GROUP BY FLAVOR
)

SELECT FLAVOR FROM B
ORDER BY TOTAL_ORDER DESC
LIMIT 3;