WITH RECURSIVE HOURS AS (
  SELECT 0 AS HOUR
  UNION ALL
  SELECT HOUR + 1 FROM HOURS WHERE HOUR < 23
)

SELECT H.HOUR AS HOUR, COUNT(a.ANIMAL_ID) AS COUNT
FROM HOURS H
LEFT JOIN ANIMAL_OUTS a ON HOUR(a.DATETIME) = h.hour
GROUP BY H.HOUR
ORDER BY H.HOUR;
