WITH MEMBERS AS (
    SELECT M.MEMBER_ID MEMBER_ID, M.MEMBER_NAME MEMBER_NAME, COUNT(R.REVIEW_ID) REVIEW_COUNT
    FROM MEMBER_PROFILE M
    JOIN REST_REVIEW R
    ON M.MEMBER_ID = R.MEMBER_ID
    GROUP BY MEMBER_ID
    ORDER BY REVIEW_COUNT DESC
), MAX_COUNT AS (
    SELECT MAX(REVIEW_COUNT) REVIEW_COUNT
    FROM MEMBERS
)

SELECT M.MEMBER_NAME MEMBER_NAME, R.REVIEW_TEXT REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM MEMBERS M
JOIN REST_REVIEW R
ON M.MEMBER_ID = R.MEMBER_ID
JOIN MAX_COUNT C
ON M.REVIEW_COUNT = C.REVIEW_COUNT
ORDER BY REVIEW_DATE, R.REVIEW_TEXT;
