SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
JOIN SKILLCODES S1 ON S1.NAME = 'Python'
JOIN SKILLCODES S2 ON S2.NAME = 'C#'
WHERE (D.SKILL_CODE & S1.CODE) = S1.CODE
   OR (D.SKILL_CODE & S2.CODE) = S2.CODE
ORDER BY D.ID;
