SELECT
    G.SCORE_SUM SCORE,
    H.EMP_NO EMP_NO,
    H.EMP_NAME EMP_NAME,
    H.POSITION POSITION,
    H.EMAIL EMAIL
FROM HR_EMPLOYEES H
JOIN (
    SELECT EMP_NO, SUM(SCORE) SCORE_SUM
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
) AS G
ON H.EMP_NO = G.EMP_NO
ORDER BY G.SCORE_SUM DESC
LIMIT 1;