WITH MAX_VIEW AS (
    SELECT MAX(VIEWS) VIEWS FROM USED_GOODS_BOARD
)

SELECT CONCAT('/home/grep/src/', B.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, F.FILE_EXT) FILE_PATH
FROM USED_GOODS_FILE F
JOIN USED_GOODS_BOARD B
ON F.BOARD_ID = B.BOARD_ID
WHERE B.VIEWS = (SELECT VIEWS FROM MAX_VIEW)
ORDER BY FILE_ID DESC;

