WITH SKILLS AS (
    SELECT D.ID, D.EMAIL, D.SKILL_CODE,
           SUM(CASE WHEN S.NAME = 'Python' THEN 1 ELSE 0 END) AS HAS_PYTHON,
           SUM(CASE WHEN S.NAME = 'C#' THEN 1 ELSE 0 END) AS HAS_CSHARP,
           SUM(CASE WHEN S.CATEGORY = 'Front End' THEN 1 ELSE 0 END) AS HAS_FRONT
    FROM DEVELOPERS D
    JOIN SKILLCODES S
    ON (D.SKILL_CODE & S.CODE) = S.CODE
    GROUP BY D.ID, D.EMAIL, D.SKILL_CODE
)

SELECT * 
FROM (
    SELECT 
        CASE
            WHEN HAS_PYTHON > 0 AND HAS_FRONT > 0 THEN 'A'
            WHEN HAS_CSHARP > 0 THEN 'B'
            WHEN HAS_FRONT > 0 THEN 'C'
            ELSE NULL
        END AS GRADE,
        ID,
        EMAIL
    FROM SKILLS
) AS GRADED_SKILLS
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID;
